// export const message = 'Hello from World!'
// export const template = '{{taskPathBasename}}'

// ===================== GENERATED CODE BELOW =====================
// Generated by @chriswa/ts-codegen (embedded template)
// Do not edit manually - changes will be overwritten
// ================================================================
export const message = 'Hello from World!'
export const template = '_simple.hbs.ts'
