import { logger } from './logger'
import { asError } from 'catch-unknown'
import * as fs from 'fs'

const cacheFilePath = './.ts-codegen.cache'

function loadCacheFile(): Map<string, boolean> {
  try {
    if (fs.existsSync(cacheFilePath)) {
      const fileContent = fs.readFileSync(cacheFilePath, 'utf-8')
      // Skip YAML comment lines (starting with #) and find the JSON content
      const lines = fileContent.split('\n')
      const jsonStartIndex = lines.findIndex((line) => !line.trim().startsWith('#') && line.trim() !== '')
      const jsonContent = lines.slice(jsonStartIndex).join('\n')
      const data = JSON.parse(jsonContent) as Record<string, boolean>
      return new Map(Object.entries(data))
    }
  }
  catch (error) {
    logger.warn(`${cacheFilePath} could not be read, ignoring file: ` + asError(error).message)
  }
  return new Map()
}
function writeCache() {
  const obj = Object.fromEntries(cacheData)
  const header = '# This file is used to support cleaning up orphaned generated files\n# Generated by @chriswa/ts-codegen - do not edit manually\n'
  const jsonContent = JSON.stringify(obj, null, 2)
  fs.writeFileSync(cacheFilePath, header + jsonContent)
}

const cacheData = loadCacheFile()

export const outputFileManager = {
  write(outputFilePath: string, content: string): boolean {
    cacheData.set(outputFilePath, true)
    writeCache()
    if (fs.existsSync(outputFilePath)) {
      const oldContent = fs.readFileSync(outputFilePath, 'utf-8')
      if (oldContent === content) {
        return false // optimization to prevent filesystem writes when the file wouldn't actually change
      }
    }
    fs.writeFileSync(outputFilePath, content)
    return true
  },
  delete(outputFilePaths: Array<string>): void {
    for (const outputFilePath of outputFilePaths) {
      if (fs.existsSync(outputFilePath)) {
        try {
          fs.unlinkSync(outputFilePath)
        }
        catch (error) {
          logger.error(`error unlinking ${outputFilePath}: ` + asError(error).message)
        }
      }
      cacheData.delete(outputFilePath)
    }
    writeCache()
  },
  getAllOutputFilePaths() {
    return Array.from(cacheData.keys())
  },
  clean() {
    this.delete(outputFileManager.getAllOutputFilePaths())
    fs.unlinkSync(cacheFilePath)
  },
}
